name: Generate SHA-256 Checksum

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  generate_sha256:
    if: "!contains(github.event.head_commit.message, 'Add SHA-256 checksum for serial_logger.py')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate SHA-256 checksum
      run: |
        sha256sum serial_logger/serial_logger.py > serial_logger/serial_logger.py.sha256

    - name: Commit SHA-256 checksum
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add serial_logger/serial_logger.py.sha256
        git commit -m 'Add SHA-256 checksum for serial_logger.py'
        git push
